### ISSUE TITLE
Tables enable expandable 

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#310]
Examples: 
- https://flowbite.com/blocks/application/crud/#crud-layout-with-expandable-rows
- https://tanstack.com/table/v8/docs/framework/react/examples/expanding?from=reactTableV7

**Comment by ahmeterenodaci** [comment]
[tanstack.com/table/v8/docs/framework/react/examples/expanding?from=reactTableV7](https://tanstack.com/table/v8/docs/framework/react/examples/expanding?from=reactTableV7) bu aradığımız şey değil.

[https://tanstack.com/table/v8/docs/framework/react/examples/sub-components](https://tanstack.com/table/v8/docs/framework/react/examples/sub-components) aradığımız şey bu.
