### ISSUE TITLE
Change filter dialog to list

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#327]
In the table, we are using a dialog to choose filter: 
![image](https://github.com/user-attachments/assets/635a1a43-13d6-404f-a290-f9626618f45f)

it would be great to have to have it as a menu like this one: 
![image](https://github.com/user-attachments/assets/5eeda6d9-e962-45f7-8a92-d2fcd7bf66b0)

Relates https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/pull/489#pullrequestreview-2234949408

**Comment by ahmeterenodaci** [comment]
![resim](https://github.com/user-attachments/assets/6b0b4208-8a45-41c9-82e5-13f5959a410c)
![resim](https://github.com/user-attachments/assets/21543e69-62d2-4591-91c5-7cd02ff9dcba)
