### ISSUE TITLE
table: add months and years navigation

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#335]
- https://daypicker.dev/docs/navigation

**Comment by ahmeterenodaci** [comment]
@a0m0rajab this feature added on v9, shadcn uses v8. Is this navigation a must?

**Comment by a0m0rajab** [comment]
Can not we implement it by using the month prop and the go to day button? 
we will have two drop down buttons, one for months and the other for years. 

It's not a must yet it's nice to have
