### ISSUE TITLE
Dialog: get rid of content and use children

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#360]
Instead of having content and content-loading we can pass children to the main component and handle the loading skeleton on the main page: 

https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/blob/d1d149c3a993454835b4840b1f986e18463e59d2/src/molecules/dialog/index.tsx#L77-L80

**Comment by eren-ayasofyazilim** [comment]
#374  We are giving everything inside action prop. 
```typescript
 {activeAction &&
        ('autoFormArgs' in activeAction || 'content' in activeAction) && (
          <CustomTableActionDialog
            open={isOpen}
            onOpenChange={setIsOpen}
            action={activeAction}
            type={activeAction?.type}
          />
        )}
``` 
Action can also be autoform and in that case we don't need content. To use children prop we need something like this but it's not logical in our case.

```typescript
<Temp>{children}</Temp>
```
