### ISSUE TITLE
bug(table): show the number of rows in the footer

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#461]
When we provide the row number of the table it does not show on the footer, the footer is fixed to 10. 
make the footer update and add a story with multiple pages (20 dummy data)

![image](https://github.com/user-attachments/assets/860bef4e-99bc-4d9f-90a6-211cebe89d9a)

**Comment by KaisAlHusrom** [comment]
please assign this issue to me

**Comment by a0m0rajab** [comment]
@KaisAlHusrom Thanks, I just assigned you

**Comment by KaisAlHusrom** [comment]
is this the solution that this issue want to resolve?
![image](https://github.com/user-attachments/assets/dc642b41-77c5-428f-9da7-36d79b795047)
![image](https://github.com/user-attachments/assets/00889cca-1dba-48c8-85a3-8229979ab965)

I added select options of row's number that will appears per page, and added more 20 fake data?
