### ISSUE TITLE
Allow to show a specific number of elements in the page

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#470]
At this moment we show 10 rows per page for as default, we need to allow the user to enter the number of rows per page to use like the next: 
![image](https://github.com/user-attachments/assets/034d0bdc-7ba6-4b85-8d0a-5cc42f44ef07)

**Comment by Suvendu-UI** [comment]
pls assign this issue to me

**Comment by a0m0rajab** [comment]
@Suvendu-UI Thanks for your interest in this, I just assigned you.

**Comment by a0m0rajab** [comment]
Hi are you still interested in this? @Suvendu-UI 
If not, I will remove you and work on this internally.

**Comment by a0m0rajab** [comment]
Done in: https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/553
