### ISSUE TITLE
table(filters): add clear all filters

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#491]
In the table filter we only add fitlers now, yet it would be great to have clear all button if we have more than 2 filters
Related page: 
![image](https://github.com/user-attachments/assets/97d2e559-4de2-4d76-8282-37fcc8195a2a)

Clear all could be on the left side of the filters as one button.
https://ayasofyazilim-clomerce.github.io/ayasofyazilim-ui/?path=/story/molecules-tables--detailed-filter

![image](https://github.com/user-attachments/assets/3985b407-276b-4987-b98e-43ac3742403d)

**Comment by KaisAlHusrom** [comment]
hello, I can solve this issue

**Comment by KaisAlHusrom** [comment]
pull request:
https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/529
