### ISSUE TITLE
Field size is not compatible with the margin of form

### ISSUE THREAD

**Issue by ahmed3alali** [ayasofyazilim-clomerce/ayasofyazilim-ui#513]
<img width="1440" alt="Screenshot 2024-10-27 at 00 34 42" src="https://github.com/user-attachments/assets/a28609ca-74a5-4337-ba23-2bfee0e94551">

**Comment by ahmed3alali** [comment]
issue solved ..

**Comment by a0m0rajab** [comment]
@ahmed3alali  can you open a PR for that?

**Comment by a0m0rajab** [comment]
Closed at https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/517
