### ISSUE TITLE
table(Async-select): enable to remove all selected elements

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#518]
when we use the select async we show the selected elements on top of the table it would be great to have an option where we clear all selected elements and clear the table state as well. 

![image](https://github.com/user-attachments/assets/26a63127-a871-4d88-8204-e0287d1ea7b3)

**Comment by KaisAlHusrom** [comment]
Can this issue be assigned to me? I'd like to work on it.

**Comment by a0m0rajab** [comment]
Feel free to work on it @KaisAlHusrom
