### ISSUE TITLE
bug(table): select async does not show the selected elements on table when opened again

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-ui#558]
how to reproduce:
- go to tables
- use select async filter
- save the filter
- open the select async filter again: you will see that the selected elements are not showed on table

**Comment by KaisAlHusrom** [comment]
can you assign this issue to me?

**Comment by a0m0rajab** [comment]
I think this was resolved by @ahmeterenodaci  few days ago. will close this for now, can you take another issue?
